#################################
# Backend
#################################
backend = "glx";
vsync = true;
use-damage = false;  # Some setups need this false for blur to work

glx-no-stencil = true;
glx-copy-from-front = false;
glx-no-rebind-pixmap = true;

#################################
# Opacity rules
#################################
opacity-rule = [
  "100:class_g = 'kitty'",
  "97:class_g = 'Nemo'",
  "75:class_g = 'Blueman-manager'",
  "90:class_g = 'gammy'",
  "75:class_g = 'cavalier'"
];

inactive-opacity = 0.99;

#################################
# Blur settings
#################################
blur-method = "dual_kawase";
blur-strength = 5;
blur-deviation = 1.0;

blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;




